language: php

sudo: false

php:
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - vendor/bin/phpcs --standard=PSR2 -np src
  - vendor/bin/phpspec run

notifications:
  email:
    on_failure: change
